### PR TITLE
Add min and max length string attributes handling

### PR DESCRIPTION
**Pull request by Loppor**
I just noticed that I didn't add the necessary documentation, will be doing this this weekend and see if I can squash the commits together 😉

### CODE REVIEW

**Comment by Loppor** [comment]
My apologies about the failed build, will add XML-docs this weekend so the build will succeed

**Comment by zvirja** [comment]
@Loppor Could you please shed more light on the scenario you are trying to cover in this PR? We already have [StringLengthAttributeRelay](https://github.com/AutoFixture/AutoFixture/blob/6ed39385298dda9c0105ff6245e3ae9c7d82a951/Src/AutoFixture/DataAnnotations/StringLengthAttributeRelay.cs#L10) to handle the `StringLength` annotation attribute. The current PR seems to handle the exactly same attribute and it isn't clear what is the purpose.

---

It would be really helpful if you could put a good description about the changes you are performing to the PR description. That allows to save a lot of time and ensure that all we clearly understand the scenario we are trying to solve/cover. Additionally that provides a good documentation if later somebody needs to refer to this PR to understand more detail about the change. The only PRs without description I could imagine are the ones which fix the typos (like #943). If you review most of the closed PRs, you can find that we always tried to follow that rule in this project. You can also review [this](http://blog.ploeh.dk/2015/01/15/10-tips-for-better-pull-requests/) guide to find a bunch of other useful tips we follow.

If it's possible, could you please alter the PR description and put a good description of your intentions?

Thank you in advance and thanks for your time and contributions! 😃

**Comment by zvirja** [comment]
@Loppor Happy holidays! 😉

Do you know whether you will have time in the nearby future to follow up on this? Just want to understand whether it should go to the v4 scope, or could be released afterwards.

Thanks 😉

**Comment by zvirja** [comment]
@Loppor Are you still interested in following up with your PR? 😉

**Comment by zvirja** [comment]
@Loppor One last chance? ☺️

**Comment by zvirja** [comment]
Closing this one due to inactivity.
Feel free to re-open the PR if you have free time to follow up on it.

Thanks for all your time!

**Pull request closed without merging**
