### PR TITLE
Exceptions don't need to be serializable in .NET Core because there a…

### PR DESCRIPTION
**Pull request by lbargaoanu**
…re no AppDomains
@ploeh If you're still not [convinced](https://github.com/AutoFixture/AutoFixture/issues/509#issuecomment-170224097), I'll add the placeholder types for .NET Core.

### CODE REVIEW

**Comment by ploeh** [comment]
Thank you for your interest in contributing to AutoFixture. FTR, I'm currently travelling, and have only limited to time to evaluate pull requests. In due time, I'll work through my backlog, but it may take weeks :flushed: :sweat:

**Comment by ploeh** [comment]
Thank you for your interest in contributing to AutoFixture.

While it may be true that there are no AppDomains in .NET Core, they are still present in the 'full' .NET framework, and I don't see that going away in the near future.

For people who want to use AutoFixture with the existing .NET framework(s), it could be a problem if we remove the `[Serializiable]` attribute from Exceptions. How do we resolve that issue?

**Comment by lukasz-pyrzyk** [comment]
> How do we resolve that issue?

Probably we can use if statement:

    #if DNX451
        [Serializable]
    #endif
    public class IllegalRequestException : Exception


Not tested.

**Comment by lbargaoanu** [comment]
I understand you've read the MS position and you disagree. Then I guess you can close this PR and I'll add the placeholder types for .NET Core in another PR.

**Comment by ploeh** [comment]
Which MS position is that?

(Sorry if I'm being dense here, but I'm currently in an airport, roaming on my phone, so it's a bit difficult for me to master the entire context.)

**Comment by ploeh** [comment]
And now, after having posted the previous message, I see that you have provided a link... Please disregard my previous comment.

**Comment by ploeh** [comment]
I need help in order to understand the current status of .NET Core. As [others have pointed out](http://weblog.west-wind.com/posts/2016/Jan/21/Microsoft-renames-ASPNET-5-to-ASPNET-Core-10), the messaging around this has been confusing. While I'm *fairly* sure that I understand that Roslyn is a compiler, I no longer understand if *Core CLR* and *.NET Core* is the same thing. I also have absolutely no clue as to the status of it, but I can see that ASP.NET Core is some months away yet.

What can we expect once .NET Core 1.0 see the light of day? Will it replace .NET, or will it exist side-by-side with the 'full' framework?

When not preparing presentations or courses on F#, most of my energy currently goes into trying to learn Haskell, so I haven't been able to follow the .NET Core situation closely.

It'd be nice with a status summary, and how it applies to AutoFixture.

I must admit that I don't (yet) find [the linked discussion](https://github.com/dotnet/roslyn/issues/3528#issuecomment-116827732) particularly illuminating. It's essentially a semi-random discussion where an issue gets closed with a curt remark that this is no longer relevant. How does a discussion about Roslyn (a compiler) even relate to .NET Core? I'm sure there's a connection, but I need help understanding what it is.

I do understand that the trend points towards AppDomains being increasingly irrelevant, but I also need to consider existing clients and users of AutoFixture. One of the difficult things about publishing and maintaining a public library like AutoFixture is that I have little insight into how people use it...

**Comment by lbargaoanu** [comment]
The original [link] (https://github.com/AutoFixture/AutoFixture/issues/509#issuecomment-170224097).
Going forward exceptions are not going to be serializable (someone said in the issue that the guidance will be changed). It doesn't matter what framework, .NET Core or the full framework. I chose two examples, EF7 and Roslyn, of projects that will support both frameworks and will not use serializable exceptions. The reason is that they are trying to stay away from conditional compilation because it can get messy. They run one binary on all frameworks. .NET Core is RC, so probably a few months away as you said.

**Comment by lbargaoanu** [comment]
The second [link](https://github.com/dotnet/roslyn/issues/3528#issuecomment-116827732) was to show how you can workaround the fact that exceptions are not serializable anymore. I guess they consider it's a corner case and the extra work is doable. Anyway, it's just as easy to add placeholder types for .NET Core :) The real problem is that we introduce conditional compilation...

**Comment by lbargaoanu** [comment]
The strategy is to wait? :)

**Comment by ploeh** [comment]
Perhaps I have things mixed up. What little knowledge I have of .NET Core is the noise regarding ASP.NET Core that filter my way. Perhaps my view of this work is tainted by that. Perhaps .NET Core is only superficially related to ASP.NET Core, in which case I look forward to become illuminated.

Based on the public information regarding progress of ASP.NET Core, however, I see no evidence that this project is stable. As long as it's unstable, I don't wish to start thrashing the AutoFixture source code, in order to try to keep it in sync.

If .NET Core, as opposed to ASP.NET Core, shows sign of stability, I will happily accept being taken to school on the topic. This is also the reason I previously [asked the questions I did](https://github.com/AutoFixture/AutoFixture/pull/511#issuecomment-173909621).

**Comment by lbargaoanu** [comment]
AutoFixture depends only on the runtime and the BCL, that's what .NET Core is. ASP.NET is higher in the stack. The changes seem to be more about naming then anything. RC means the API is frozen, RTM is [Q1 2016](https://github.com/dotnet/core/blob/master/roadmap.md) Also versioning is not all or nothing. You depend on a number of packages and you choose what version you want for each package. Any question I missed? :)
About the issue at hand. This seems clear enough. I don't see how that could change in the near future.
About the [MailAddress issue](https://github.com/AutoFixture/AutoFixture/issues/404#issuecomment-171943540). That might be implemented eventually...
It doesn't look like anything serious to me. It's a little tricky to support both frameworks but that will always be the case. Many projects did it already (nUnit, xUnit, AutoMapper, Json.NET). I guess waiting is also a plan, but I doubt that in six months time the conversation will be much different.

**Comment by ploeh** [comment]
> RC means the API is frozen

It's possible that I'm misinformed, but everything I hear about this is that all the beta releases were really alphas, and that the Release Candidate isn't a release candidate in any usual sense of the term.

As far as I understand, alone the decision to rename everything to .NET Core has triggered uniform renaming of namespaces.

Is there any official documentation that states that .NET Core really, unconditionally will have no breaking changes from now until it actually releases? And even so, can we trust it, in light of the project's history?

**Comment by lbargaoanu** [comment]
I don't think the real world works that way :) I guess if you don't trust it, you just don't.

**Comment by ploeh** [comment]
[I'm not alone](https://twitter.com/adamralph/status/697791925668200449).

**Comment by lbargaoanu** [comment]
I would guess that's because people actually use it on .NET Core. And that makes sense.

**Pull request closed without merging**
