### PR TITLE
Add support for SortedList<,> Issue #622

### PR DESCRIPTION
**Pull request by sbrockway**
I mimicked what @rahulpnath did for SortedDictionary<,>.

### CODE REVIEW

**Comment by sergeyshushlyapin** [comment]
To fix the failing build #680 need to be merged.

**Comment by sbrockway** [comment]
@sergeyshushlyapin you are saying that AutoFixture:master has to accept Pull Request #680 before my Pull Request will pass the AppVeyour build?  Or that I have to pull 680 into my fork?  I checked and my fork is caught up with AutoFixture:master.  How would I pull in 680 to my fork, if that is what I need to do?

**Comment by sergeyshushlyapin** [comment]
> AutoFixture:master has to accept Pull Request #680

Exactly. That is what I'm waiting for in #665 and #679 ;)

**Comment by ploeh** [comment]
#680 is merged now.

**Comment by sbrockway** [comment]
Awesome, looks like appveyor build passed as well now.

**Comment by ploeh** [comment]
Thank you for your contribution :+1: It's now live as [AutoFixture 3.50.0](https://www.nuget.org/packages/AutoFixture/3.50.0).

**Comment by ploeh** [comment]
I often make a release tweet when a new minor (or major) version of AutoFixture is out. In such a tweet, I mention the contributor. If you have a Twitter account, and you'd like me to do that, please tell me your Twitter handle.

**Comment by sbrockway** [comment]
No Twitter post. Thanks though, it was fun!

**Pull request merged**
