### PR TITLE
Enables running NUnit2 tests from dotnet cli

### PR DESCRIPTION
**Pull request by aivascu**
- Enables running NUnit2 tests from VS 2019 and dotnet cli
- Upgrades the minimum NUnit2 version to `v2.7.1`
- Adds reference to `NUnitV2.Core` package
- Removes `References` directory

### CODE REVIEW

**Review by zvirja — APPROVED** [review]
WOW! That is just so awesome! 🤩🤩🤩
I'm very glad that you found this way. Simplified life a lot!

**Review by ecampidoglio — APPROVED** [review]
LGTM. 👍

**Comment by zvirja** [comment]
@aivascu  BTW, I just noticed that we violated SemVer in this PR. We changed the supported NUnit version. It’s not allowed, as this update could potentially break some environments.

I would want us to be very strict about it and change it in major updates only.

**Comment by aivascu** [comment]
@zvirja I didn't make a release yet. 
I can revert the changes and reopen the PR for the v5 branch.

**Comment by zvirja** [comment]
I would suggest that to play safe, unless you have strong opinion against it. Sorry for the inconvenience 😕

**Pull request merged**
