### PR TITLE
Implements empty string and whitespace string behavior expectation

### LINKED ISSUE #896: EmptyStringBehaviorExpectation/WhitespaceOnlyStringBehaviorExpectation
I think it would be a valuable addition for GuardClauseAssertion as it is a quite common case to have guards for empty/whitespace-only strings. What do you think?

### PR DESCRIPTION
**Pull request by aivascu**
This PR resolves #896 and is inspired by #1005 

- Implements empty string behavior expectation
- Implements white space string behavior expectation
- Implements `GuardClauseAssertion` tests

### CODE REVIEW

**Comment by aivascu** [comment]
Hello @moodmosaic, @zvirja 
Thank you for the reply. Let me know if I need to make any changes.

**Comment by aivascu** [comment]
@ecampidoglio @moodmosaic @adamchester could you any of you review this pr?
@zvirja doesn't seem to be available at this moment.

**Comment by zvirja** [comment]
@aivascu The commits in this PR are a bit detailed, so I would suggest you to squash changes on merge. If you would like, we could discuss when to squash and when to not 😉

**Comment by aivascu** [comment]
Thank you, @zvirja! 
I agree the commits were a bit too verbose. 😅
I have squashed the commit as you requested.

**Pull request merged**
