### PR TITLE
Revert "Enables running NUnit2 tests from dotnet cli"

### PR DESCRIPTION
**Pull request by aivascu**
Reverts AutoFixture/AutoFixture#1198 due to breaking SemVer policies

### CODE REVIEW

**Comment by zvirja** [comment]
@aivascu Should we revert it entirely, or there is a way to still run it on .NET Core for that old version?

**Review by zvirja — APPROVED** [review]

**Comment by aivascu** [comment]
@zvirja the older versions do not work with .net core cli. The test runner was updated recently for v2, just for that purpose.

**Comment by zvirja** [comment]
@aivascu Can't we just update NUnit version for the unit test project only? It should be backward compatible and must work.

**Comment by zvirja** [comment]
Anyway, don't want this to take much of your time. If you find it easier to just cherry-pick fix for v5, just go with it.

**Pull request merged**
