### PR TITLE
Remove some more NoSpecimen requests

### PR DESCRIPTION
**Pull request by tiesmaster**
I'd thought, I'll pitch in a little bit for this. I hope that's ok ;)

### CODE REVIEW

**Comment by moodmosaic** [comment]
Thank you for your contribution :+1:

This is looking good to me. Since it contains breaking changes, it will only be applied to the v4 branch, similar to PR #489.

**Comment by moodmosaic** [comment]
The `build-release.sh` script succeeds without warnings on my machine.

**Comment by moodmosaic** [comment]
Very nice! We're getting closer to #475, which is great :smiley:

**Comment by ploeh** [comment]
:+1: Thank you!

**Pull request merged**
