### PR TITLE
Update Fare and System.ComponentModel.Annotations

### PR DESCRIPTION
**Pull request by benjaminoerskov**
### Description
Update Fare and System.ComponentModel.Annotations

### Closed issues
#1481

### Checklist

- [x] Reviewed the [contribution guidelines](https://github.com/AutoFixture/AutoFixture/blob/master/CONTRIBUTING.md)
- [x] Linked the issue(s) the PR closes
- [ ] Implemented automated tests and checked coverage
- [ ] Provided inline documentation comments for new public API
- [ ] Ran the full solution [build and validation](https://github.com/AutoFixture/AutoFixture#build) locally

### CODE REVIEW

**Review by KayanSilva — APPROVED** [review]

**Comment by benjaminoerskov** [comment]
Thanks for the approve @KayanSilva 
Im not sure what to do now though? The checks are not succeeding, but I have not changed anything regarding logging (which is the error its throwing).
I can also see that a AutoFixture.Xunit3 is coming. Maybe this will fix the security concerns of these dependencies, meaning I could just close this PR?

**Comment by KayanSilva** [comment]
Sure @benjaminoerskov 
"I'm reading the issue on the xUnit page and it seems to be well underway, so we can definitely wait for xUnit3. https://github.com/xunit/xunit/discussions/3006

**Comment by aivascu** [comment]
@benjaminoerskov thank you for the PR. 
Your PR is fine, however the pipeline on `master` is broken because AppVeyor silently deprecated some target frameworks that v4 of AutoFixture is targeting.
I cannot fix it without either changing the target framework, which I can't do because AutoFixture made a pledge to follow SemVer, or changing the pipeline with would create heaps of conflicts with the v5 branch.
The only way is to wait for v5, which already upgrades the dependencies to safe versions, or use the v5 preview.

**Comment by benjaminoerskov** [comment]
Thank you for the response @KayanSilva @aivascu 
I'll close the PR and patiently wait for the new xUnit instead.

**Pull request closed without merging**
