### PR TITLE
Convert to auto-implemented getter-only properties (pt. 7)

### PR DESCRIPTION
**Pull request by ErikSchierboom**

### CODE REVIEW

**Comment by moodmosaic** [comment]
This is looking good! There seems to be a failing check that's currently blocking this from getting merged.

**Comment by ErikSchierboom** [comment]
@moodmosaic Could it be that it was an error in the AppVeyor service itself? If I run the build script on this PR it builds just fine. Perhaps you could rerun the commit in AppVeyor?

**Comment by moodmosaic** [comment]
@ErikSchierboom thank you for investigating this :+1:

Unfortunately I don't know how to do that in AppVeyor, but I'm guessing that @ecampidoglio does :smiley:

**Comment by ecampidoglio** [comment]
I triggered a new build for this specific PR. Unfortunately, there is no way to do that on the AppVeyor portal so I had to do it through their [web API](https://www.appveyor.com/docs/api/projects-builds#start-build-of-pull-request-github-only). :sunglasses:

**Comment by moodmosaic** [comment]
Now _that_ was l33t :+1: :bowtie: :satisfied:

**Pull request merged**
