### PR TITLE
Fix for #628 (FakeItEasy 2 support)

### PR DESCRIPTION
**Pull request by caloggins**

### CODE REVIEW

**Comment by ploeh** [comment]
Thank you for your interest in contributing to AutoFixture!

Do I understand it correctly that this pull request proposes _changing_ the existing `AutoFakeItEasy` package?

**Comment by caloggins** [comment]
That's what I did. Was that not the intent of the issue?

Not sure why the check failed. Ran the build script locally.

**Comment by ploeh** [comment]
> Was that not the intent of the issue?

No, the intent described in #628 is to create a new library called _AutoFixture.AutoFakeItEasy2_, which can be released side-by-side with _AutoFixture.AutoFakeItEasy_. In this way, we enable users to migrate at their own pace.

**Comment by caloggins** [comment]
Completely misread it.

**Comment by ploeh** [comment]
No worries :smile: If you want to take a shot at that approach, feel free to submit another pull request :smiley_cat:

**Pull request closed without merging**
