### PR TITLE
Follow aaa style in unit test projects

### LINKED ISSUE #927: Suggestion: follow the "Arrange Act Assert" style for tests
Currently our tests follow the clumsy [Four-Phase Test](http://xunitpatterns.com/Four%20Phase%20Test.html) style to describe the test body. I don't like that at all, as it looks like some old-school stuff which doesn't play nice with xUnit. My concerns:
- The `// Teardown` phase is always empty in xUnit tests as it creates a `sut` per test, without need to `restore` it.
- The `// Fixture setup`,  `// Exercise System` and `// Verify Outcome` looks too verbose, while `// arrange`, `// act` and `// assert` are more laconic. If you don't create test from a template, it's much simpler to write those words (it's always hard to write `exercise` without typos 😅).

Therefore, @moodmosaic if you don't have any strong objections (I hope you don't), I would like to switch us to 3 phase tests and use it all our the tests. It will allow me to feel satisfaction during the test creation, rather than pain 😖

### PR DESCRIPTION
**Pull request by micheleissa**
Closes #927 
I'm planning to have a commit per project as you can see from my two commits so far.

Status:
- [x] AutoFakeItEasyUnitTest
- [x] AutoFixture.NUnit2.UnitTest
- [x] AutoFixture.NUnit3.UnitTest
- [x] AutoFixture.SeedExtensions.UnitTest
- [x] AutoFixture.xUnit.UnitTest
- [x] AutoFixture.xUnit2.UnitTest
- [x] AutoFixtureDocumentationTest
- [x] AutoFixtureUnitTest
- [x] AutoFoqUnitTest
- [x] AutoMoqUnitTest
- [x] AutoNSubstituteUnitTest
- [x] AutoRhinoMockUnitTest
- [x] Idioms.FsCheckUnitTest
- [x] IdiomsUnitTest

-Eissa

### CODE REVIEW

**Comment by zvirja** [comment]
@micheleissa Everything looks great so far! 👍💯 The only thing I'd change is the message of the first commit - it's better to align it with name of the second one (and reflect the actual project that has been modified).

If currently you don't have enough capacity to work on this issue, it might make sense to make PRs more granular and merge them one by one. Otherwise, code quickly becomes obsoleted as new tests are added in other PRs. Later it might be harder to merge the code.. 😕

**Comment by micheleissa** [comment]
@zvirja can I do different PRs on the same branch I'm working on for different commits?

**Comment by zvirja** [comment]
No, you cannot. My point was that after you accomplished some part of work, we could merge it. After that you can create a new PR and migrate other projects (or part of them).

All that stuff makes sense only if there is a significant delay between the changes (e.g. you are busy). Otherwise, it definitely is an overhead.

**Comment by micheleissa** [comment]
Ok, actually it will get busy for me soon but still I want to accomplish some part of the work and planning to finish it. Maybe by the end of this week we can reveiw the progress and see if it is a good merge and go from there?
Question: for the new PR it will be on the same branch I created?
Sorry if I'm asking too many questions, I use Git at work but we don't do PRs 😕 and this is my first code change on an open source project.

**Comment by zvirja** [comment]
> for the new PR it will be on the same branch I created?

After I merge and close this PR, we'll get a regular merge commit in git history. After that, usually, you remove the old branch as it becomes obsolete. If you want to perform a new contribution, you need to create a new one on top of the latest `master`. You are free to re-use the old branch name if you wish - it's totally up to you 😉

---


@micheleissa If you don't mind, I'll review and merge this PR at the current stage. The reason is that I need to perform changes in AutoFixture project and it might be a bit hard to resolve the merge conflicts later.

**Comment by zvirja** [comment]
I've also updated the subject with a list of project that should be modified. That will allow to track progress much better. Please update the status as long as you progress.

**Comment by micheleissa** [comment]
@zvirja sounds good. I'm fine with you merging now and I can re-create the branch.

**Comment by zvirja** [comment]
@micheleissa I've reviewed all the remaining test project and rebased the branch on top of the latest `master`. 

Thanks A LOT for the GREAT and HARD work you did changing the stuff. I do understand how much efforts it required for you! 🥇🍷

**Comment by zvirja** [comment]
@micheleissa Now your contribution is a part of the `master`. Thanks again for your time! 😉

Happy holidays! 🎉

**Comment by zvirja** [comment]
@micheleissa BTW, your PR is our 500th closed PR! Hooray 🌟⭐️🏇😄

**Pull request merged**
