### PR TITLE
Adapting build scripts for Visual Studio 2015

### PR DESCRIPTION
**Pull request by Pvlerick**
A start for fixing #432.

I do get the error reporter in the issue thread when building, so these will have to be fixed.

### CODE REVIEW

**Comment by adamchester** [comment]
Looks good so far. Related issue: @ploeh should we have a CI build connected to GitHub so we can see the build results here? I believe you have teamcity setup already, is that right? We just need to configure it to report back to GitHub?

**Comment by ploeh** [comment]
Looks good.

@adamchester, from the discussion in #432, I deduce that you have an installation of Visual Studio 2015 without Visual Studio 2013. Have you tried running the build scripts in this pull request on that system? If so, is all good?

I haven't gone around to installing Visual Studio 2015 yet, so my system only has Visual Studio 2013. Both `build-release.sh` and `BuildRelease.ps1` work on my system with this pull request.

If I can get confirmation that it also works on a system with Visual Studio 2015, I'll merge this pull request.

**Comment by ploeh** [comment]
When it comes to connecting a CI build to GitHub, I was actually contemplating decommissioning the centralised build for AutoFixture, because I consider a build server brittle, unreliable, and a central point of failure.

Yet another thing I need to blog about...

**Comment by adamchester** [comment]
@ploeh I look forward to that blog post, and I look forward to watching the arguments it generates :smile: 

I can confirm that `powershell .\BuildRelease.ps1` correctly builds on a fresh Windows 10 with only VS 2015 installed (no prior versions ever on this machine). There are zero warnings.

From VS 2015 developer command prompt, typing `msbuild BuildRelease.msbuild` (_note: this means MSBuild v14 is used_ which is a different, newer MSBuild than the normal MSBuild AutoFixture uses) still generates the warnings I mentioned in #432:

```
       "C:\repo\autofixture\BuildRelease.msbuild" (CompleteBuild target) (1) ->
       "C:\repo\autofixture\Src\AutoFixture.NUnit2.sln" (default target) (8) ->
       "C:\repo\autofixture\Src\AutoFixture.NUnit2\AutoFixture.NUnit2.csproj" (default target) (9) ->
       (ResolveCodeAnalysisRuleSet target) ->
         C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.CSharp.CurrentVersion.targets(133,9): warning MSB3884: Could
        not find rule set file "AutoFixture.NUnit2.ruleset". [C:\repo\autofixture\Src\AutoFixture.NUnit2\AutoFixture.NU
       nit2.csproj]


       "C:\repo\autofixture\BuildRelease.msbuild" (CompleteBuild target) (1) ->
       "C:\repo\autofixture\Src\AutoFixture.NUnit2.sln" (default target) (8:2) ->
       "C:\repo\autofixture\Src\AutoFixture.NUnit2\AutoFixture.NUnit2.csproj" (default target) (9:8) ->
         C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.CSharp.CurrentVersion.targets(133,9): warning MSB3884: Could
        not find rule set file "AutoFixture.NUnit2.ruleset". [C:\repo\autofixture\Src\AutoFixture.NUnit2\AutoFixture.NU
       nit2.csproj]


       "C:\repo\autofixture\BuildRelease.msbuild" (CompleteBuild target) (1) ->
       "C:\repo\autofixture\Src\AutoFixture.xUnit.net.sln" (default target) (17:2) ->
       "C:\repo\autofixture\Src\AutoFixture.xUnit.net\AutoFixture.xUnit.net.csproj" (default target) (18:5) ->
         C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.CSharp.CurrentVersion.targets(133,9): warning MSB3884: Could
        not find rule set file "AutoFixture.xUnit.net.ruleset". [C:\repo\autofixture\Src\AutoFixture.xUnit.net\AutoFixt
       ure.xUnit.net.csproj]


       "C:\repo\autofixture\BuildRelease.msbuild" (CompleteBuild target) (1) ->
       "C:\repo\autofixture\Src\AutoRhinoMock.sln" (default target) (32:2) ->
       "C:\repo\autofixture\Src\AutoRhinoMock\AutoRhinoMock.csproj" (default target) (34:5) ->
         C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.CSharp.CurrentVersion.targets(133,9): warning MSB3884: Could
        not find rule set file "Migrated rules for AutoRhinoMock.ruleset". [C:\repo\autofixture\Src\AutoRhinoMock\AutoR
       hinoMock.csproj]

    4 Warning(s)
    0 Error(s)
```

I believe it's safe to call this a separate issue, just wanted to note it.

**Comment by Pvlerick** [comment]
I think @moodmosaic has a system where only VS 2015 is installed.

On my side, having VS 2015 on my system and 2013 uninstalled, I get the warnings when running the scripts.

**Comment by adamchester** [comment]
@Pvlerick which warnings do you get?

**Comment by Pvlerick** [comment]
@adamchester the ones you [mentioned here](https://github.com/AutoFixture/AutoFixture/issues/432#issuecomment-127515967).

**Comment by adamchester** [comment]
@Pvlerick OK that is due to MSBuild v14.0 being used, right?

**Comment by adamchester** [comment]
@ploeh just on the topic of builds, it's somewhat easy for us to setup our own CI builds... The problem is, it would be nice to see the big warning against a pull request (eg. Warning when build could not be completed, or big red error for a build failure). It allows discussion/diagnosis/training/etc.

In case anyone is interested here is mine for AutoFixture https://ci.appveyor.com/project/adamchester/autofixture

Here are some settings for appveyor (relevant here because you can test the CS 2015 build along with other configurations):
```yaml 
version: 1.0.{build}
os:
- Default Azure
- Visual Studio 2015
clone_depth: 1
build:
  project: BuildRelease.msbuild
  parallel: true
  verbosity: minimal
artifacts:
- path: NuGetPackages/*
```

**Comment by Pvlerick** [comment]
@adamchester Yes I think so.

**Comment by moodmosaic** [comment]
Running `build-release.sh` on a clean Windows 8.1 environment with only Visual Studio 2015 installed yields 2 warnings:

```
Build succeeded.

"h:\Projects\AutoFixture\BuildRelease.msbuild" (default target) (1) ->
(Test target) ->
  MSBUILD : warning MSB6006: "nunit-console.exe" exited with code -2146232576.
[h:\Projects\AutoFixture\BuildRelease.msbuild]
  MSBUILD : warning MSB6006: "nunit-console.exe" exited with code -2146232576.
[h:\Projects\AutoFixture\BuildRelease.msbuild]

    2 Warning(s)
    0 Error(s)
```

Then, I get prompted to download and install .NET Framework 3.5:

image

**Comment by ploeh** [comment]
That sounds a bit inconclusive to me. Should I pull, or shouldn't I?

This pull request doesn't have to make everything *perfect*. The important point is that it makes the situation *better* for someone, without making it worse for someone else (that's a Pareto improvement, for anyone who cares).

It's not causing me any problems, so I'd be happy to pull, but I also don't want to cause trouble for other people.

**Comment by Pvlerick** [comment]
@ploeh I think it's better to wait that we figure out what is wrong for the "VS2013 and VS2015 on the same machine" setup, since it's likely to be common.

**Comment by moodmosaic** [comment]
I run a couple of builds, and the scripts are now executing successfully on each environment:

**Visual Studio 2015**

After installing .NET Framework 3.5 (which was required also by TestDriven.Net) the `build-release.sh` and `BuildRelease.ps1` scripts run without warnings and without errors.

**Visual Studio 2013 and Visual Studio 2015**

The `build-release.sh` and `BuildRelease.ps1` scripts run without warnings and without errors.

---

At this point, based on the results on my machine, we could be good to go.

**Comment by adamchester** [comment]
:+1: I think it makes things better, the other issues already existed.

**Comment by Pvlerick** [comment]
After updating my system to Windows 10 yesterday, it builds with no warnings, go figure...

@ploeh  I think we are goot to go :-)

**Comment by ploeh** [comment]
Thank you for your contribution!

Since this is a build/compile concern only, there's no release associated with this pull request.

**Pull request merged**
