### PR TITLE
Add support for SortedList<,> Issue #622

### PR DESCRIPTION
**Pull request by sbrockway**
Implemented a ISpecimenBuilder relay as @ploeh suggested in the StackOverflow question linked to Issue #622 .
I noticed the obsolete NoSpecimen(request), but followed the pattern I saw elsewhere of using it with disabling warning 618.
I can make the switch to the 0 param ctor for my implementation if you'd prefer.

Let me know if I missed anything.  My first OSS try.  I want to learn if I missed a step in process/convention.
Or if I missed something in the implementation.
Thanks for the opportunity with the Jump In label on the issue.

### CODE REVIEW

**Comment by sbrockway** [comment]
Thanks as well to @Mykezero.  I learned from, and mimiced what you did for #624

**Comment by ploeh** [comment]
Thank you for your pull request! Looking through the commit history, it looks like you started implementing the feature using a specification, but then changed the implementation to use a relay instead. What was the motivation for doing that?

**Comment by sbrockway** [comment]
@ploeh I started out mimicing what @Mykezero did which was using the specification.  I created a DictionaryFavoringConstructorQuery : IMethodQuery hoping that it would receive and handle the request, but it did not work.  I registered a snippet in the map building section to use MethodInvoker but as I recall, it never invoked my DictionaryFavoringConstructorQuery.  I should have checked it in, so there would be a record to review.

**Comment by ploeh** [comment]
Now that #629 already chose the route of using Specifications, I'd be keen on pursuing that way to solve the issue here as well, if at all possible. Otherwise, I'm a bit concerned that it'll be confusing to maintainers that there are more than one way of doing seemingly related things.

Is there anything I can do to help going in that direction?

**Comment by sbrockway** [comment]
I'll try the DictionaryFavoringConstructorQuery again, and reach out if I get stuck again.

**Pull request closed without merging**
