### PR TITLE
[WIP] Fake build windows

### PR DESCRIPTION
**Pull request by ErikSchierboom**
This PR adds a FAKE script that has the exact same functionality as the existing MSBuild file. This will allow for C# 6 features to be used (see #500). It also opens up the possibility for cross-platform building. Hopefully, I managed to get the dependencies right, which is why I marked this as a WIP.

It is also marked as WIP as I haven't been able to get the cross-platform stuff working. While everything builds fine on Windows, on my Mac it got 24 compile errors. It turns out the Mono compiler did not like some of the `<seecref>` comment references. To fix this, the types references needed to be prefixed with "T:" (as per [this link](http://mono.1490590.n4.nabble.com/Errors-with-XML-Comments-during-build-td3009482.html)). This solved the problem of the 24 compile errors, but now the next problem was that the xUnit runner threw an exception:

<pre>
ystem.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object

Server stack trace: 

  at Xunit.TestCaseMessage..ctor (ITestCase testCase) <0x31bcc00 + 0x0000c> in <filename unknown>:0 

  at Xunit.TestMessage..ctor (ITest test) <0x31c5f48 + 0x00027> in <filename unknown>:0 

  at Xunit.TestStarting..ctor (ITest test) <0x31c5f20 + 0x00017> in <filename unknown>:0 

  at (wrapper remoting-invoke-with-check) Xunit.TestStarting:.ctor (Xunit.Abstractions.ITest)

  at Xunit.TestClassCallbackHandler.OnStart (System.Xml.XmlNode xml) <0x31c5190 + 0x0012f> in <filename unknown>:0 

  at Xunit.TestClassCallbackHandler.OnXmlNode (System.Xml.XmlNode node) <0x31c50d8 + 0x0006a> in <filename unknown>:0 

  at Xunit.XmlNodeCallbackHandler.System.Web.UI.ICallbackEventHandler.RaiseCallbackEvent (System.String eventArgument) <0x304ec08 + 0x0008b> in <filename unknown>:0 

  at (wrapper managed-to-native) System.Runtime.Remoting.RemotingServices:InternalExecute (System.Reflection.MethodBase,object,object[],object[]&)

  at System.Runtime.Remoting.RemotingServices.InternalExecuteMessage (System.MarshalByRefObject target, IMethodCallMessage reqMsg) <0x1a9a540 + 0x00234> in <filename unknown>:0 

Exception rethrown at [0]: 

  at <0x00000 + 0x00000> <unknown method>

  at (wrapper remoting-invoke) System.Web.UI.ICallbackEventHandler:RaiseCallbackEvent (string)

  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)

  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x3263cb0 + 0x00093> in <filename unknown>:0 

  --- End of inner exception stack trace ---

  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x3263cb0 + 0x000e7> in <filename unknown>:0 

  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) <0x323f530 + 0x00039> in <filename unknown>:0 

  at Xunit.Sdk.ExecutorCallback+CallbackEventHandlerCallback.Notify (System.String value) <0x32c88e0 + 0x00067> in <filename unknown>:0 

  at Xunit.Sdk.Executor.OnTestStart (ITestCommand command, Xunit.Sdk.ExecutorCallback callback) <0x32d1670 + 0x00037> in <filename unknown>:0 

  at Xunit.Sdk.Executor+RunTests+<>c__DisplayClass12.<.ctor>b__10 (ITestCommand command) <0x32d1640 + 0x0001b> in <filename unknown>:0 

  at Xunit.Sdk.TestClassCommandRunner.Execute (ITestClassCommand testClassCommand, System.Collections.Generic.List`1 methods, System.Predicate`1 startCallback, System.Predicate`1 resultCallback) <0x32cefb0 + 0x002f3> in <filename unknown>:0 

  at Xunit.Sdk.Executor+RunTests+<>c__DisplayClass12.<.ctor>b__f () <0x32cee80 + 0x00103> in <filename unknown>:0 

  at Xunit.Sdk.Executor.ThreadRunner (System.Object threadStart) <0x32ceaa8 + 0x0004d> in <filename unknown>:0 

  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) <0x32ce9f8 + 0x0008b> in <filename unknown>:0 

  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) <0x32ce698 + 0x001b6> in <filename unknown>:0 

  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) <0x32ce660 + 0x00027> in <filename unknown>:0 

  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) <0x32ce5a8 + 0x0004f> in <filename unknown>:0 

  at System.Threading.ThreadHelper.ThreadStart (System.Object obj) <0x32ce500 + 0x0004b> in <filename unknown>:0 
</pre>

As it turned out, this error occured in four different test projects:

- AutoFixtureUnitTest
- AutoNSubstituteUnitTest
- IdiomsUnitTest
- SemanticComparisonUnitTest

I did not find a way to fix this, but I'm not an experienced Mono user though.

Another side-effect of "fixing" the `<seecref>` comments, is that the Windows build now failed. In particular, the `Verify` build fails on the `SemanticComparison` project with the following errors:

<pre>
       "D:\Programmeren\AutoFixture\Src\AutoFixture.sln" (Rebuild target) (1) ->
       "D:\Programmeren\AutoFixture\Src\SemanticComparison\SemanticComparison.csproj" (Rebuild target) (3) ->
       (RunCodeAnalysis target) ->
         D:\Programmeren\AutoFixture\Src\SemanticComparison\MemberInfoExtension.cs(48): error CA1811: Microsoft.Perform
       ance : 'MemberInfoExtension.ToUnderlyingType(this MemberInfo)' appears to have no upstream public or protected c
       allers. [D:\Programmeren\AutoFixture\Src\SemanticComparison\SemanticComparison.csproj]
         D:\Programmeren\AutoFixture\Src\SemanticComparison\ProxyGenerator.cs(368): error CA1811: Microsoft.Performance
        : 'ProxyGenerator.FindCompatibleProperty(this Type, string)' appears to have no upstream public or protected ca
       llers. [D:\Programmeren\AutoFixture\Src\SemanticComparison\SemanticComparison.csproj]
         D:\Programmeren\AutoFixture\Src\SemanticComparison\ProxyGenerator.cs(345): error CA1801: Microsoft.Usage : Par
       ameter 'members' of 'ProxyGenerator.GetParameters(this IEnumerable<MemberInfo>, object, List<Type>)' is never us
       ed. Remove the parameter or use it in the method body. [D:\Programmeren\AutoFixture\Src\SemanticComparison\Seman
       ticComparison.csproj]
         D:\Programmeren\AutoFixture\Src\SemanticComparison\ProxyGenerator.cs(355): error CA1811: Microsoft.Performance
        : 'ProxyGenerator.Matches(this List<Type>, Type)' appears to have no upstream public or protected callers. [D:\
       Programmeren\AutoFixture\Src\SemanticComparison\SemanticComparison.csproj]
         D:\Programmeren\AutoFixture\Src\SemanticComparison\ProxyGenerator.cs(362): error CA1811: Microsoft.Performance
        : 'ProxyGenerator.MatchProperty(this Type, string)' appears to have no upstream public or protected callers. [D
       :\Programmeren\AutoFixture\Src\SemanticComparison\SemanticComparison.csproj]

---------------------------------------------------------------------
  1) Building D:\Programmeren\AutoFixture\Src\AutoFixture.sln failed with exitcode 1.
  2) CA1811: D:\Programmeren\AutoFixture\Src\SemanticComparison\MemberInfoExtension.cs(48,0): Microsoft.Performance : 'M
emberInfoExtension.ToUnderlyingType(this MemberInfo)' appears to have no upstream public or protected callers.
  3) CA1811: D:\Programmeren\AutoFixture\Src\SemanticComparison\ProxyGenerator.cs(368,0): Microsoft.Performance : 'Proxy
Generator.FindCompatibleProperty(this Type, string)' appears to have no upstream public or protected callers.
  4) CA1801: D:\Programmeren\AutoFixture\Src\SemanticComparison\ProxyGenerator.cs(345,0): Microsoft.Usage : Parameter 'm
embers' of 'ProxyGenerator.GetParameters(this IEnumerable<MemberInfo>, object, List<Type>)' is never used. Remove the pa
rameter or use it in the method body.
  5) CA1811: D:\Programmeren\AutoFixture\Src\SemanticComparison\ProxyGenerator.cs(355,0): Microsoft.Performance : 'Proxy
Generator.Matches(this List<Type>, Type)' appears to have no upstream public or protected callers.
  6) CA1811: D:\Programmeren\AutoFixture\Src\SemanticComparison\ProxyGenerator.cs(362,0): Microsoft.Performance : 'Proxy
Generator.MatchProperty(this Type, string)' appears to have no upstream public or protected callers.
</pre>

In this PR, I have omitted the commit that "fixed" the `<seecref>` comments so this PR can build on Windows fine. If you are interested in the commit that does include these type comment fixed, check out the [fake-build branch](https://github.com/ErikSchierboom/AutoFixture/commit/c704ececf3a9971a29972ddc6e69b94a7d846065).

To make the PR easier to verify, I have split it into several commits.

### CODE REVIEW

**Comment by ploeh** [comment]
Thank you for your interest in contributing to AutoFixture :+1: 

This pull request touches 1,132 files. How can I review that?

Is there any way to split this work up into multiple smaller pull requests?

**Comment by ErikSchierboom** [comment]
@ploeh Well, I split the PR into 4 commits:

1. Everything related to the build script.
2. The files for the xunit.runner.console package.
3. The files for the FSharp.Core package.
4. The files for the FAKE package.

You can individually view each commit by clicking on it. The commits are listed right above your comment. This is the same as splitting it into several PR's, right?

**Comment by ploeh** [comment]
Sorry, that was a knee-jerk reaction on my part. (_In general_, splitting a pull request into several commits doesn't help much, because I'd still need to review all the file changes. Going commit by commit could even mean _more_ work for the reviewer, if multiple commits touch the same file.)

Adding or updating NuGet packages is, however, a special case. You've done the right thing, and it _does_ make it easier to review.

I was still surprised to see that FAKE should contain 1,088 files, since this would be a dramatic increase from the 500-odd files I'm used to seeing (although that's already a lot).

1,088 files are too many for GitHub to display, but I pulled the fork to look at it locally. If you look at the `Packages` directory in this pull request, you'll see that there are two FAKE folders:

```
~/Documents/ploeh/AutoFixture (ErikSchierboom-fake-build-windows)
$ ll -d Packages/FAKE*
drwxr-xr-x 1 mark 197609 0 Feb 11 11:24 Packages/FAKE.4.11.3/
drwxr-xr-x 1 mark 197609 0 Feb 11 11:25 Packages/FAKE.4.19.0/
```

Did you add FAKE 4.11.3 by accident?

**Comment by ErikSchierboom** [comment]
@ploeh Great to hear that this PR is in the correct format. As for the FAKE files, I did indeed accidentally also include the 4.11.3 version. I removed those files and updated the PR.

Note: as the build.cmd file accidentally also referred to the 4.11.3 file, I also had to amend the first commit. This means that all four commits now have different hashes.

**Comment by ploeh** [comment]
It builds and reports no errors on my Windows machine. This is the build summary:

```
---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target                          Duration
------                          --------
CleanReleaseFolder              00:00:00.0257379
CleanDebug                      00:00:05.6250248
CleanVerify                     00:00:06.5205173
CleanRelease                    00:00:05.0206906
CleanAll                        00:00:00.0001017
Verify                          00:02:24.3258004
Build                           00:00:38.9682482
Test                            00:00:00.0001048
CopyToReleaseFolder             00:00:00.0628837
ZipReleaseFiles                 00:00:00.5698540
CreateTemporaryNuGetSpecFiles   00:00:00.0229204
NuGetPack                       00:00:13.3366821
CleanTemporaryNuGetSpecFiles    00:00:00.0129718
DeleteTestResultFiles           00:00:00.0025568
CompleteBuild                   00:00:00.0000709
Total:                          00:03:34.7369486
Status:                         Ok
---------------------------------------------------------------------
```

Notice that the _Test_ step is completed in less than a millisecond. Could it be that the tests don't run?

**Comment by ErikSchierboom** [comment]
@ploeh That is odd, I'll look into it!

**Comment by ErikSchierboom** [comment]
@ploeh I made a simple mistake in my dependency chain. The updated PR fixed this. Note that in my version of the build script, the `Test` and `Build` targets are both empty targets, the actual work is done in `TestOnly` and `BuildOnly`, which they depend on.

This is how it looks like now on my machine:

<pre>
---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target                          Duration
------                          --------
CleanReleaseFolder              00:00:00.0095783
CleanDebug                      00:00:03.8917553
CleanVerify                     00:00:04.7774931
CleanRelease                    00:00:04.4996069
CleanAll                        00:00:00.0000359
Verify                          00:01:33.9924106
BuildOnly                       00:00:32.7597371
Build                           00:00:00.0000748
TestOnly                        00:00:26.4789301
Test                            00:00:00.0000845
CopyToReleaseFolder             00:00:00.0347197
ZipReleaseFiles                 00:00:00.4058676
CreateTemporaryNuGetSpecFiles   00:00:00.0103019
NuGetPack                       00:00:07.4038690
CleanTemporaryNuGetSpecFiles    00:00:00.0046522
DeleteTestResultFiles           00:00:00.0021996
CompleteBuild                   00:00:00.0000292
Total:                          00:02:54.3927971
Status:                         Ok
---------------------------------------------------------------------
</pre>

**Comment by ploeh** [comment]
This looks extremely promising :+1: 

As far as I can tell, the only thing missing is the ability to sign the assemblies with a strong name. Yes, I do realise that strong name signing is old-fashioned, and will not be supported on .NET in the future, but I still consider it a breaking change to remove strong name signatures from AutoFixture. While we probably will release AutoFixture 4 without strong names, we must keep signing AutoFixture 3.

If you look at `build-release.sh`, you'll see that it has the option of being passed a `.snk` file from the command-line. This is is how I build and release a new version of AutoFixture.

If the `build.sh` script could do that as well, I think we could retire the old MSBuild-based build script. Would that be possible?

**Comment by ErikSchierboom** [comment]
I managed to get the key signing working; the PR has been updated. To get it to work, you pass in an extra command-line parameter with its key equal to `signkey`. As an example, this is how to sign using a `test.snk` file in the same directory as the `build.cmd` file:

    .\build.cmd -ev signkey test.snk

Unfortunately, signing the assemblies breaks the unit test task:

<pre>
    Ploeh.AutoFixture.AutoFoq.UnitTest.FixtureIntegrationTest.FixtureSuppliesValuesToAbstractGenericTypeWithNonDefaultCo
nstructor [FAIL]
      System.IO.FileLoadException : Could not load file or assembly 'Foq, Version=1.5.1.0, Culture=neutral, PublicKeyTok
en=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
    Ploeh.AutoFixture.AutoFoq.UnitTest.FoqMethodQueryTest.SelectMethodsDefineCorrectParameters(Ploeh.TestTypeFoundation.
AbstractType) [FAIL]
      System.IO.FileLoadException : Could not load file or assembly 'Unquote, Version=3.1.0.0, Culture=neutral, PublicKe
yToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
</pre>

You can still verify that the signing works by running:

     .\build.cmd buildonly -ev signkey test.snk

I assume that it is the assemblies in the NuGet package that need to be signed, but that task depends on the "CopyToReleaseFolder" task, which in turn depends on the "Test" task.

How would you like this fixed?

**Comment by ploeh** [comment]
It looks like the proposed solution doesn't respect the strong name [opt-out that e.g. AutoFoq defines](https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFoq/AutoFoq.fsproj#L15). The current build script respects that...

**Comment by ErikSchierboom** [comment]
@ploeh I think I fixed the strong signing issue. Could you check if it works?

**Comment by ploeh** [comment]
Fantastic work :+1: Thank you so much for doing this :tada: 

In principle, we ought to be able to delete the old build scripts already, but I'd like to keep them around for one or two releases, just in case anything turns out not to work after all. Not that I expect this, but me experience has taught me to be a bit conservative...

**Comment by ErikSchierboom** [comment]
My pleasure! 

I already figured you'd like to keep the old build scripts around for a little while, which is why I left them in :)

And now I can finally start with using C# 6 features in AutoFixture, which is how this all started.

**Comment by ploeh** [comment]
I've just discovered that the new build script doesn't create symbols NuGet packages. Instead, all source code is being packaged into the library NuGet package itself.

**Comment by ErikSchierboom** [comment]
@ploeh I'll have a look!

**Comment by ErikSchierboom** [comment]
@ploeh I think I managed to fix this. I just submitted PR #546 that fixes this.

**Comment by ploeh** [comment]
@ErikSchierboom, that was fast! Thank you :+1:

**Pull request merged**
