### PR TITLE
Remove obsolete files from projects

### PR DESCRIPTION
**Pull request by zvirja**
I removed the `Zero29` tool and MSBuild community tasks as they are no longer used.

Also I normalized the NuGet tool. Currently we have 2 copies of the tool. I removed one of copy and updated other one to the latest available version.

Let me know if you see any issues with this cleanup.

### CODE REVIEW

**Comment by moodmosaic** [comment]
This makes sense to review and merge after we merge #755, or do I miss something obvious? 😃

**Comment by zvirja** [comment]
@moodmosaic These two PRs doesn't seem to be related to each other. Nevertheless, I've just merged #755. I'll close/re-open this PR to trigger a fresh merge and CI validation.

**Comment by moodmosaic** [comment]
@klimisa, are you able to follow these changes? Besides @ecampidoglio, @adamchester, and me, it'd be helpful if you can follow along, because AFAICT these changes are related to the release process.

**Comment by zvirja** [comment]
@moodmosaic @klimisa Well, this particular PR isn't related to the release process somehow - it's a simple obsoletes cleanup 😃

**Pull request merged**
