### PR TITLE
Add .net standard support to AutoFoq

### PR DESCRIPTION
**Pull request by josh-degraw**
In reference to #1143, this PR adds .net standard support for `AutoFoq`.

### CODE REVIEW

**Comment by aivascu** [comment]
Hello @josh-degraw! 
Thank you for the contribution.
It looks like the current build configuration ([visual studio 2015](https://www.appveyor.com/docs/windows-images-software/)) does not support .NET Core 3+. 
I'll see if the are any implications to the upgrade and get back to you.

**Comment by josh-degraw** [comment]
@aivascu Okay, if it's easier I can just change the new target framework I for the unit tests to .NET Core 2.2

**Comment by aivascu** [comment]
@josh-degraw I think changing the target framework, for now, might be the better plan.
I have tried to test the build under the VS 2019 environment, with no success.
I will upgrade the tests to use .NET Core 3, once I am more familiar with F# and FAKE.

**Comment by zvirja** [comment]
Should we also update readme file to mark it netstandard compatible?

**Comment by aivascu** [comment]
You are correct. I missed that.

**Pull request merged**
