### PR TITLE
Enabling build `netstandard1.3` via `dotnet build`,

### PR DESCRIPTION
**Pull request by adamchester**
using FAKE.Dotnet and CLI 1.0.0-preview2-003121

Opening this now to check if it still builds. Ref #404

### CODE REVIEW

**Comment by adamchester** [comment]
Note this is a prototype of just one possible way to build and verify `Ploeh.AutoFixture.dll` against `netstandard1.3’. It doesn't even publish the dll in the nuget package yet.
,

**Comment by tylerohlsen** [comment]
I hear support for netstandard in msbuild / csproj is coming and project.json files are getting deprecated.  You may want to hold off on this change until that occurs.  Just my suggestion.

**Comment by cvbarros** [comment]
I agree, I think it should be held until definitive word about .csproj.

2016-10-27 0:04 GMT-02:00 Tyler Ohlsen <notifications@github.com>:

**Comment by adamchester** [comment]
FTR, I too agree. It's too hard to make the build and project work at the moment; the tools are too lacking

**Comment by adamchester** [comment]
Sorry I don't have time to keep going with this.

Closing so others aren't blocked waiting for me to finish this - I have no plans to.

**Pull request closed without merging**
